adding Dose filter to xmipptomo
I2PC/scipion-em-xmipptomo pull request #101
Opened 2022-12-23 16:43 UTC by Vilax

2022-12-24 09:43 UTC, fede-pe requested changes
Maybe subtomogram extraction protocols shouldn't be here?

2022-12-24 10:52 UTC, Vilax commented
why subtomogram extraction should be here?
I do not see the relation between these two protocols

2023-02-06 14:15 UTC, pconesa approved these changes

2023-03-31 11:49 UTC, fede-pe approved these changes

2023-03-31 11:49 UTC, merged