Add attribute which is used by ancestor classes to indicate the usage…
I2PC/scipion-em-xmipptomo pull request #25
Opened 2020-08-18 09:40 UTC by JorMaister

… of tomo options

2020-08-19 07:15 UTC, DStrelak reviewed
are you sure that this is a correct file? 
Because it's flexalign for tomo version, so it makes sense it will be ued for tomography

2020-08-19 07:55 UTC, JorMaister commented
Hi, @DStrelak ,
This is the best way I found to make other protocols involved, such as xmipp3 --> /protocol_movie_correlation.py, be aware of they are working with tomography, when it's the case. Thus, main protocol being executed is the one which has to indicate it to the others called. But, there can be better ways to do it, for sure. Any suggestions are more than welcome!

2020-09-29 11:32 UTC, pconesa requested changes

2020-09-29 11:32 UTC, pconesa commented on xmipptomo/protocols/protocol_flexalign.py
> +        import os
COuld you please remove this line! I know is mine! :man_facepalming:

2020-09-29 11:34 UTC, pconesa approved these changes

2020-09-29 11:34 UTC, merged

2020-09-29 12:22 UTC, pconesa commented on xmipptomo/protocols/protocol_flexalign.py
> +        import os
I did it already.