Transformation Matrix Scoring
I2PC/scipion-em-xmipptomo pull request #44
Opened 2021-02-12 12:52 UTC by DavidHerreros

Two new protocols added:

- `protocol_align_transform` performs a rigid alignment of the transformations associated with a series of Subtomograms to a common axis
- `protocol_score_transform` gives a distance score by comparing the corresponding alignments associated with different subtomograms using quaternions

`protocol_score_transform` has a test that will remain commented until the datasets available for tomography include the appropriate data

2021-02-15 15:16 UTC, EstrellaFG requested changes

2021-02-15 15:16 UTC, EstrellaFG commented on xmipptomo/protocols/protocol_score_transform.py
> +
I think it is a good idea to add a validation function to check that both input SetOfSubtomograms have transformation matrix. Something like: 
`def _validate(self):`
 `       validateMsgs = []`
     `   for subtomo in self.input.get().iterItems():`
        `    if not subtomo.hasTransform():`
             `   validateMsgs.append('Please provide subtomograms which have transformation matrix in "inputAlignment".')`
      `  return validateMsgs`

2021-02-17 13:05 UTC, DavidHerreros commented on xmipptomo/protocols/protocol_score_transform.py
> +        # acquisition = TomoAcquisition()
Yes, I have left it commented so we can fix it in the future once the acquisition issue is solved

2021-02-17 14:11 UTC, EstrellaFG commented on xmipptomo/protocols/protocol_score_transform.py
> +        # acquisition = TomoAcquisition()
great!

2021-02-17 14:11 UTC, EstrellaFG approved these changes

2021-02-17 14:50 UTC, merged