new scheme for tomo menu
I2PC/scipion-em-xmipptomo pull request #68
Opened 2021-11-22 11:41 UTC by EstrellaFG

Please review that your protocols are in the correct section :)

2021-11-22 12:27 UTC, fede-pe commented
Since split TS is used in both cryoCare and Monotomo pipelines, might it be in TS preprocess @Vilax?

2021-11-22 12:46 UTC, Vilax requested changes
I agree with Fede, I would move the split TS to preprocess. Doing that it is perfect :)

2021-11-22 13:30 UTC, DavidHerreros approved these changes

2021-11-25 09:32 UTC, fede-pe approved these changes

2021-11-25 09:55 UTC, merged